routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\User;
use App\Role;
use App\Department;
use App\Task;
use App\TaskStatus;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin/users', 'AdminUsersController')->except([
    'show', 'create'
]);
Route::resource('admin/tasks', 'AdminTasksController')->except([
    'show'
]);
Route::get('admin', [
    'as' => 'admin',
    'uses' => 'AdminController@index'
]);
Route::resource('/admin/department', 'AdminDeptController')->except([
    'show'
]);

Route::put('task/complete/{id}', [
    'as' => 'task.complete',
    'uses' => 'TasksController@completed'
]);

resources/views/includes/adminBanner.blade.php
<div class="jumbotron text-center p-5 mt-4">
    <h1>A Office Task Queue Admin Dashboard</h1>
    <p class="lead">Create task for various departments</p>
    <strong>Version 1.0</strong>
</div>

resources/views/includes/adminSidebar.blade.php
<div class="col-md-2 bg-light py-2">
    <h6><strong>USER SECTION</strong></h6>
    <ul class="nav flex-column">
        <li class="nav-item"><a href="{{ route('admin') }}" class=" nav-link {{ Request::is('admin') ? 'active' : ''}}">Add New User</a></li>
        <li class="nav-item"><a href="{{ route('users.index') }}" class="nav-link {{ Request::is('admin/users') ? 'active' : ''}}">View All Users</a></li>
    </ul>

    <hr class="bg-light">
    
    <h6><strong>TASK SECTION</strong></h6>
    <ul class="nav flex-column">
        <li class="nav-item"><a href="{{ route('tasks.create') }}"class="nav-link {{ Request::is('admin/tasks/create') ? 'active' : ''}}">Add New Task</a></li>
        <li class="nav-item"><a href="{{ route('tasks.index') }}"class="nav-link {{ Request::is('admin/tasks') ? 'active' : ''}}">View All Tasks</a></li>
    </ul>

    <hr class="bg-light">
    
    <h6><strong>DEPARTMENT SECTION</strong></h6>
    <ul class="nav flex-column">
        <li class="nav-item"><a href="{{ route('department.create') }}"class="nav-link {{ Request::is('admin/department/create') ? 'active' : ''}}">Add New Department</a></li>
        <li class="nav-item"><a href="{{ route('department.index' ) }}"class="nav-link {{ Request::is('admin/department') ? 'active' : ''}}">View All Departments</a></li>
    </ul>
</div>

resources/views/includes/message.blade.php
{{-- @if (count($errors))
    @foreach ($errors->all() as $error)
        {{ $error }}
    @endforeach
@endif --}}

@if (session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif

@if (session('failed'))
    <div class="alert alert-danger">
        {{ session('failed') }}
    </div>
@endif