routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\User;
use App\Role;
use App\Department;
use App\Task;
use App\TaskStatus;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('admin/users', 'AdminUsersController')->except([
    'show', 'create'
]);
Route::resource('admin/tasks', 'AdminTasksController')->except([
    'show'
]);
Route::get('admin', [
    'as' => 'admin',
    'uses' => 'AdminController@index'
]);
Route::resource('/admin/department', 'AdminDeptController')->except([
    'show'
]);

Route::put('task/complete/{id}', [
    'as' => 'task.complete',
    'uses' => 'TasksController@completed'
]);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'role_id', 'department_id'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function role() {
        return $this->belongsTo('App\Role');
    }

    public function department()
    {
        return $this->belongsTo('App\Department');
    }


    public function photo(){
        return $this->hasOne('App\Photo');
    }
    public function isAdmin($role){

        if($this->role->name == $role){
            return true;
        }

        return false;
    }
}

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content');
    
@include('includes.adminBanner')

    <div class="container">
        <div class="row">
            @include('includes.adminSidebar')
            <div class="col-2">
                <img src="{{ $user->photo ? $user->photo->image : ' ' }}" alt="" class="img-fluid">
            </div>
            <div class="col">
                <div class="col">
                    @include('includes.message')
                    
                    <h2>Edit User</h2>
                    @if (count($errors))
                    @foreach ($errors->all() as $error)
                        {{ $error }}
                    @endforeach
                @endif
                    {!!  Form::model($user, ['method'=>'PATCH', 'action'=>['AdminUsersController@update', $user->id], 'files'=>true]) !!}
                        <div class="form-group">
                            {{ Form::label('name', 'Name:') }}
                            {{ Form::text('name', null, ['class'=> $errors->has('name') ? 'form-control is-invalid' : 'form-control'])}}
                            @foreach ($errors->get('name') as $name)
                                <span class="invalid-feedback mb-3">{{ $name }}</span>
                            @endforeach
                        </div>
                        <div class="form-group">
                            {{ Form::label('password', 'Password:') }}
                            {{ Form::password('password', ['class'=>'form-control'])}}
                        </div>
                        {{-- <div class="form-group">
                            {{ Form::label('confirm', 'Confirm Password:') }}
                            {{ Form::password('confirm', ['class'=>'form-control'])}}
                        </div> --}}
                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ Form::label('role', 'Select Role:') }}
                                    {{ Form::select('role_id', $roles, null,  ['class'=>'form-control'])}}
                                </div>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    {{ Form::label('department', 'Select Department:') }}
                                    {!! Form::select('department_id', $departments , null, ['class'=>'form-control']) !!}
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            {{ Form::file('image', ['class'=>' form-control'])}}
                        </div>
                        <div class="form-group">
                            {{ Form::submit('Edit User', ['class'=>'btn btn-primary'])}}
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>

    </div>
@endsection

resources/views/admin/user/view.blade.php
@extends('layouts.app')

@section('content')
    @include('includes.adminBanner')

    <div class="container">
        <div class="row">
            @include('includes.adminSidebar')
            <div class="col">
                <div class="col">
                    @include('includes.message')
                    <h2>View All Users</h2>
                    @if (count($users))
                        <table class="table">
                            <thead>
                                <tr class=" bg-info">
                                    <th>S/N</th>
                                    <th>Images</th>
                                    <th>Name</th>
                                    <th>Email</th>
                                    <th>Role</th>
                                    <th>Department</th>
                                    <th>Created_at</th>
                                    {{-- <th>Updated_at</th> --}}
                                    <th></th>
                                    <th></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $i=>$user)
                                    <tr>
                                        <td>{{ $i+1 }}</td>
                                        <td><img src="{{ $user->photo ? $user->photo->image : 'No' }}" alt="" height="30"></td>
                                        <td>{{ $user->name }}</td>
                                        <td>{{ $user->email }}</td>
                                        <td>{{ $user->role->name }}</td>
                                        {{-- <td>{{ $user->department->name }}</td> --}}
                                        @if (is_null($user->department_id))
                                            <td>No Dept</td>
                                        @else
                                            <td>{{ $user->department->name }}</td>
                                        @endif
                                        <td>{{ $user->created_at->diffForHumans() }}</td>
                                        {{-- <td>{{ $user->updated_at->diffForHumans() }}</td> --}}
                                        <td>
                                            <a href="{{ route('users.edit', $user->id) }}" class="btn btn-primary">Edit</a>
                                        </td>
                                        <td>
                                            {{ Form::open(['method' => 'DELETE', 'action' => ['AdminUsersController@destroy', $user->id]]) }}
                                                {{ Form::submit('Delete', ['class'=>'btn btn-danger'])}}
                                            {{ Form::close() }}
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    @else
                        <h2>No user</h2>
                    @endif
                </div>
            </div>
        </div>

    </div>
@endsection